# Generated by Django 6.0.5 on 2026-05-22 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluxogramas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('contexto', models.TextField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil')], default='medio', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fluxograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_clinicos', to='fluxogramas.fluxograma')),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('aberta', 'Aberta'), ('multipla_escolha', 'Múltipla escolha')], default='aberta', max_length=30)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('resposta_esperada', models.TextField(blank=True, null=True)),
                ('palavras_chave', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('caso_clinico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='casos.casoclinico')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('caso_clinico', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='RespostaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.TextField()),
                ('correta', models.BooleanField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('pontuacao', models.IntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_usuarios', to='casos.questao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_casos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='PassoRaciocinio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos_raciocinio', to='casos.questao')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('questao', 'ordem')},
            },
        ),
    ]
